name: uniswap_core
description: Code shared across Dart Uniswap SDK versions.
version: 1.0.0
repository: https://github.com/zagmi/uniswap_core
homepage: https://github.com/zagmi/uniswap_core

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  convert: ^3.1.1
  tiny_invariant: ^1.0.0+1
  zagmi: ^0.0.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
